spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ashokit
    url: jdbc:h2:mem:testdb
    username: ashokit
  jpa:
    hibernate:
      ddl-auto: update
plan-api:
  messages:
    planSaveSucc: Plan Saved Successfully
    planSaveFail: Plan Save Failed
    planUpdateSucc: Plan Updated Successfully
    planUpdateFail: Plan Update Failed
    planDeleteSucc: Plan Deleted Successfully
    planDeleteFail: Plan Delete Failed
    planStatusChange: Plan Status Changed Successfully
    planStatusChangeFail: Plan Status Change Failed